version: '2'
services:
  web:
    extends:
      file: docker-compose-common.yml
      service: web
    build:
      context: .
      args:
        - ENV=dev
        - BASE_IMAGE=node:8-alpine
        - NODE_ENV=dev
    image: sre-web-dev
    volumes:
    - .:/usr/src/app/
    - /usr/src/app/node_modules
