apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "sae-workbench.fullname" . }}
  labels:
    app: {{ template "sae-workbench.name" . }}
    chart: {{ template "sae-workbench.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "sae-workbench.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sae-workbench.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: SESSION_COOKIE_SECURE
              value: "false"
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "sae-workbench.fullname" . }}-secrets
                  key: cookieSecret
            - name: SERVER_PATH
              value: {{ .Values.serverPath }}
            - name: OIDC_HOST
              value: {{ .Values.auth.host }}
            - name: OIDC_USERINFO_PATH
              value: {{ .Values.auth.userInfoPath }}
            - name: OIDC_ISSUER
              value: {{ .Values.auth.issuer }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.auth.clientID }}
            - name: OIDC_CLIENT_SECRET
              value: {{ .Values.auth.clientSecret }}
            - name: OIDC_AUTH_URL
              value: {{ .Values.auth.authorizationEndpoint }}
            - name: OIDC_TOKEN_URL
              value: {{ .Values.auth.tokenEndpoint }}
            - name: OIDC_USERINFO_URL
              value: {{ .Values.auth.userInfoURL }}
            - name: OIDC_LOGOUT_URL
              value: {{ .Values.auth.logoutURL }}
            - name: OIDC_CALLBACK_URL
              value: {{ .Values.auth.callbackURL }}
            - name: OIDC_SCOPE
              value: {{ .Values.auth.scope }}
            - name: LINK_TO_OCWA
              value: {{ .Values.links.ocwa }}
            - name: LINK_TO_OCWADL
              value: {{ .Values.links.ocwadl }}
            - name: LINK_TO_PROJECTSC
              value: {{ .Values.links.projectsc }}
            - name: LINK_TO_SELFSERVE
              value: {{ .Values.links.selfserve }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
