apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sae-workbench.fullname" . }}-secrets
  labels:
    app: {{ template "sae-workbench.name" . }}
    chart: {{ template "sae-workbench.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  cookieSecret: {{ .Values.cookieSecret | b64enc }}