apiVersion: v1
kind: Service
metadata:
  name: {{ template "sae-workbench.fullname" . }}
  labels:
    app: {{ template "sae-workbench.name" . }}
    chart: {{ template "sae-workbench.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: {{ template "sae-workbench.name" . }}
    release: {{ .Release.Name }}
  {{- if .Values.service.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  {{- if .Values.service.sessionAffinity.timeout }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinity.timeout }}
  {{- end }}
  {{- end }}
